# Generated by Django 4.2.10 on 2024-02-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='eye_x',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='eye_y',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='eye_z',
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_x_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_x_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_y_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_y_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_z_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='eye_z_in',
            field=models.FloatField(default=0),
        ),
    ]
