# Generated by Django 5.0.2 on 2024-02-23 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lidar", "0004_completedscan_completed_scan_added_scan_scan_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
