# Generated by Django 5.0.2 on 2024-03-06 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lidar", "0005_vehicle_vehicle_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_body_class",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(13),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_weight_class",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
            preserve_default=False,
        ),
    ]
