# Generated by Django 5.0.3 on 2024-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0008_alter_scan_lidar_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='lidar_scan',
            field=models.FileField(upload_to=''),
        ),
    ]
