# Generated by Django 5.0.3 on 2024-03-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0008_remove_scan_eye_x_ft_remove_scan_eye_x_in_and_more'),
        ('lidar', '0009_alter_scan_lidar_scan'),
    ]

    operations = [
    ]
