# Generated by Django 5.0.3 on 2024-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0010_merge_20240315_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='lidar_scan',
            field=models.FileField(upload_to='lidar_scans/'),
        ),
    ]
