# Generated by Django 5.0.3 on 2024-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0010_merge_20240315_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='windshield_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='lidar_scan',
            field=models.FileField(upload_to='lidar_scans/'),
        ),
    ]
