# Generated by Django 5.0.3 on 2024-03-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0010_merge_20240315_1558'),
        ('lidar', '0012_alter_scan_lidar_scan'),
    ]

    operations = [
    ]
