# Generated by Django 5.0.3 on 2024-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0013_merge_20240325_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='windshield_removed',
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_status',
            field=models.TextField(default='uploaded'),
        ),
    ]
