# Generated by Django 5.0.2 on 2024-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lidar", "0016_completedscan_driver_eye_heights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedscan",
            name="vehicle_back",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="completedscan",
            name="vehicle_front",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="completedscan",
            name="vehicle_left",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="completedscan",
            name="vehicle_right",
            field=models.FloatField(default=0),
        ),
    ]
