# Generated by Django 4.2.10 on 2024-02-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lidar_scan', models.FileField(upload_to='lidar_scans/')),
                ('eye_x', models.FloatField()),
                ('eye_y', models.FloatField()),
                ('eye_z', models.FloatField()),
                ('driver_side_start', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lidar.vehicle')),
            ],
        ),
    ]
