# Generated by Django 4.2.10 on 2024-02-07 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lidar', '0002_remove_scan_eye_x_remove_scan_eye_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvp_xs', models.CharField(max_length=2160, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('nvp_ys', models.CharField(max_length=2160, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('area', models.FloatField()),
                ('raw_scan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lidar.scan')),
            ],
        ),
    ]
